/* ==========================================================================
   notlar-data.js : Ders ders HMGS notları
   Dört sınavın (460 soru) ders bloğu, tekrar eden konu, tuzak ve sayı
   ölçümlerinden süzüldü; şüpheli her sayı soru metni ve cevap anahtarıyla
   yeniden kontrol edildi (25 Eylül 2026).

   Alanlar
     cikan : [konu, soru sayısı, kaç sınavda]   (sayı yoksa null)
     tuzak : { y: sınavın kurduğu yanlış, d: doğrusu }  ya da düz not
     ezber : [değer, ne]
     yok   : ölçülen sınavlarda hiç sorulmayan başlıklar

   © 2026 Yusuf GÜNAY, Tüm Hakları Saklıdır.
   ========================================================================== */

export const SINAV = { soru: 120, dakika: 155, saniye: 77.5 };

export const DERSLER = [
  {
    id: 'anayasa', ad: 'Anayasa Hukuku', aralik: [1, 6], soru: 6, ters: 4,
    ozet: 'Yasama ağırlıklı; cevap çoğu zaman bir sayı.',
    cikan: [
      ['TBMM toplantı ve karar yeter sayısı', 5, 4],
      ['Seçim, ara seçim, demokrasi araçları', 4, 4],
      ['Millî Güvenlik Kurulu', 2, 2],
      ['Meclis soruşturması ve Yüce Divan', 2, 2],
      ['Cumhurbaşkanı ve kanunlar (geri gönderme)', 2, 2],
      ['Siyasi partiler', 2, 1],
    ],
    tuzak: [
      'Toplantı yeter sayısı ile karar yeter sayısını yer değiştiriyorlar; bir soruda dört şık bu ikisinin kombinasyonuydu.',
      '151, 301, 360 ve 400 aynı soruda yan yana duruyor. Sayıyı değil, **hangi işleme ait olduğunu** ezberle.',
      { y: 'Siyasi parti grubu dokunulmazlığın kaldırılmasını görüşebilir.', d: 'Görüşemez, karar alamaz.' },
      { y: 'MGK toplantısına kural olarak 6 bakan katılır.', d: 'Asıl üye 4 bakan (Adalet, Millî Savunma, İçişleri, Dışişleri); gündeme göre çağrılan bakan eklenir.' },
      'Varsayımsal "A Devleti" kurgusu geliyor: seçmenlerin imzasıyla milletvekillerini toplu görevden alma = **temsilcilerin azli**.',
    ],
    ezber: [
      ['200', 'Toplantı yeter sayısı, üye tamsayısının üçte biri'],
      ['151', 'Karar yeter sayısı alt sınırı, tamsayının dörtte birinin bir fazlası'],
      ['301', 'Geri gönderilen kanunu aynen kabul, salt çoğunluk'],
      ['360', 'Meclis soruşturması açma, beşte üç, gizli oy'],
      ['400', 'Yüce Divan\'a sevk, üçte iki, gizli oy'],
      ['15 kişi', 'Meclis soruşturması komisyonu'],
      ['3 + 3 ay', 'Yüce Divan yargılaması, ek süreyle en çok 6 ay'],
      ['90 gün', 'İlin hiç milletvekili kalmazsa ara seçim: boşalmadan 90 gün sonraki ilk pazar'],
      ['5 ay', 'Somut normda AYM\'nin karar süresi; geçerse mahkeme yürürlükteki hükme göre karar verir'],
    ],
    yok: 'Anayasa değişikliği usulü ve normlar hiyerarşisi doğrudan sorulmadı.',
    sinavda: 'Bu blokta ters kök neredeyse yok. Soru çoğu zaman doğrudan bir sayı istiyor; sayıyı işleme bağlamadan işaretleme.',
  },
  {
    id: 'aymyargi', ad: 'Anayasa Yargısı', aralik: [7, 9], soru: 3, ters: 33,
    ozet: 'Neredeyse tamamı 6216 sayılı Kanun metninden.',
    cikan: [
      ['Bireysel başvuru', 2, 2],
      ['Yargılamanın yenilenmesi', 1, 1],
      ['Genel Kurulun görevleri', 1, 1],
      ['Devlet sırrı, bilgi ve belge istenmesi', 1, 1],
      ['Üyelerin yükümlülükleri', 1, 1],
      ['AYM üyeliğine avukat kontenjanı', 1, 1],
    ],
    tuzak: [
      { y: 'Üyeler karar oylamasında çekimser oy kullanabilir.', d: 'Çekimser oy kullanılamaz.' },
      { y: 'Bilgi ve belge talebini süresinde karşılamayanlar hakkında doğrudan soruşturma yapılamaz.', d: 'Yapılabilir.' },
      'İki ayrı sınavda doğru cevap **15 gün**, ama biri karara bağlama süresi, öteki mazeret sonrası başvuru. Başlangıç anını oku.',
      'CBK\'yı Anayasa\'ya aykırı bulan mahkeme davayı **AYM** kararına kadar geri bırakır; Danıştay, Yargıtay çeldirici.',
      'Avukat kontenjanı: baro başkanlarının gösterdiği adaylardan en çok oy alan **3 aday** içinden **TBMM** seçer.',
    ],
    ezber: [
      ['1 hafta', 'Milletvekilliğinin düşürülmesine karşı AYM\'ye iptal başvurusu'],
      ['15 gün', 'AYM\'nin bu iptal istemini karara bağlama süresi'],
      ['15 gün', 'Bireysel başvuruda mazeretin kalkmasından sonra başvuru'],
      ['30 gün', 'Bireysel başvuru süresi'],
      ['60 gün', 'İptal davası, Resmî Gazete\'de yayımdan itibaren'],
      ['2/3', 'Siyasi parti kapatma kararı'],
    ],
    sinavda: '"Kural olarak yapılamaz" kalıbı iki sınavda ters çevrildi. 6216\'daki istisnaları bil.',
  },
  {
    id: 'idare', ad: 'İdare Hukuku', aralik: [10, 15], soru: 6, ters: 11,
    ozet: 'Memur rejimi her sınavda; karar alıntısından kavram adı.',
    cikan: [
      ['657 sayılı Kanun, memur rejimi', 7, 4],
      ['Kamulaştırma', 3, 2],
      ['Kamu Denetçiliği Kurumu (6328)', 2, 2],
      ['Yetki devri, idari vesayet, hiyerarşi', 2, 2],
      ['Bilgi edinme, soruşturma izni, belediye organları', 3, 3],
    ],
    tuzak: [
      'Yetki devri, idari vesayet, hiyerarşi, yetki saptırması, imza devri beşlisi iki sınavda aynen geldi. Alıntıdaki tarif hangisine uyuyor, onu bul.',
      { y: 'KDK\'ya başvuru dava açma süresini durdurmaz.', d: 'Dava süresi içinde yapılan başvuru işlemeye başlamış süreyi durdurur.' },
      { y: 'Görevden uzaklaştırma bir disiplin cezasıdır.', d: 'İhtiyati tedbirdir.' },
      'Kamulaştırmada iptal davası **idari yargıda**, bedel ve düzeltim **adli yargıda**.',
      'Devlet mallarının haczedilememesi, kamu hizmetinin **süreklilik** ilkesinin sonucudur.',
    ],
    ezber: [
      ['30 iş günü', 'Bilgi edinme itirazına Kurulun karar süresi (30 gün, 7 iş günü çeldirici)'],
      ['1 kademe', 'Avukatlık stajı sonrası memurlukta kademe ilerlemesi'],
    ],
    yok: 'İdari sözleşme hiç sorulmadı; kolluk yalnız bir kez dolaylı geçti.',
    sinavda: 'Karar alıntılı soruda cevap iki kelimelik bir kavram adı. Alıntıyı okuyup adı kendin söyle, sonra şıklara bak.',
  },
  {
    id: 'iyuk', ad: 'İdari Yargılama Usulü', aralik: [16, 18], soru: 3, ters: 44,
    ozet: 'Yürütmenin durdurulması ve duruşma; kök çoğu zaman ters.',
    cikan: [
      ['Yürütmenin durdurulması', 3, 2],
      ['Duruşma esasları', 3, 2],
      ['Danıştay duruşmasında savcı', 2, 2],
      ['Danıştay teşkilatı (2575)', 2, 2],
      ['İlk inceleme kararları', 1, 1],
    ],
    tuzak: [
      { y: 'İdare ve vergi mahkemelerinde duruşmada savcı bulunur.', d: 'Savcı yalnız Danıştay\'daki duruşmada bulunur.' },
      { y: 'Yürütmenin durdurulması istemi savunma alınmadan reddedilemez.', d: 'Reddedilebilir.' },
      { y: 'Disiplin cezalarında yürütmenin durdurulması istenemez.', d: 'İstenebilir.' },
      { y: 'Taraflardan yalnız biri gelirse duruşma yapılmaz.', d: 'Yapılır.' },
      'İlk inceleme karar adlarını ayır: görev ve yetki, süre aşımı, dilekçe reddi, **incelenmeksizin ret**.',
      'Başkanlar Kurulu, Başkanlık Kurulu, tetkik hâkimi gibi adlar **2575**\'te geçer, İYUK\'ta değil.',
    ],
    ezber: [
      ['30 gün', 'Duruşma davetiyesi, duruşmadan en az bu kadar önce'],
      ['ikişer', 'Duruşmada taraflara söz verilme sayısı'],
      ['30 gün', 'Görev yönünden ret kesinleşince görevli yerde dava'],
    ],
    yok: 'Dava açma süresi sayısal olarak hiç sorulmadı; temyiz de yok.',
    sinavda: 'Bloğun neredeyse yarısı ters kök. Kökü iki kez oku.',
  },
  {
    id: 'medeni', ad: 'Medeni Hukuk', aralik: [19, 33], soru: 15, ters: 34,
    ozet: 'Sınavın en büyük bloğu. Boşanma her sınavda.',
    cikan: [
      ['Boşanma', 9, 4],
      ['Dernek', 4, 3],
      ['Yasal miras payı hesabı', 4, 4],
      ['Mirasın reddi, resmî tasfiye, miras ortaklığı', 4, 2],
      ['Fiil ehliyeti ve kısıtlama', 5, 3],
      ['Evlenme butlanı, hısımlık engeli', 3, 2],
      ['Vasiyetname', 3, 3],
      ['Tapu sicili', 3, 3],
      ['Taşınır rehni, ipotek', 3, 3],
      ['Zilyetlik devri, üst hakkı, gaiplik', 6, 3],
    ],
    tuzak: [
      'Ters kökte doğru cevap çoğu zaman **tek kelimesi bozulmuş** kanun hükmü. Aşağıdakilerin hepsi gerçek sorulardan:',
      { y: 'Boşanmadan doğan dava hakları 6 ayda zamanaşımına uğrar.', d: '1 yıl, hükmün kesinleşmesinden.' },
      { y: 'Bağımsız bölüm üzerinde ayrıca üst hakkı kurulabilir.', d: 'Kurulamaz.' },
      { y: 'Malik, harap olan intifa konusu malı onarmakla yükümlüdür.', d: 'Yükümlü değildir.' },
      { y: 'Tenkis önce sağlararası kazandırmalardan yapılır.', d: 'Önce ölüme bağlı tasarruflardan.' },
      { y: 'Genel kurulda üye vekâletle sınırsız oy kullanabilir.', d: 'Her üyenin bir oyu var, oyunu kendisi kullanır.' },
      'Hayata kast ve pek kötü muamelede dava hakkı **süreye bağlı**; haysiyetsiz hayatta eş **her zaman** dava açabilir.',
      'Butlan ve zilyetlik devri sorularında **aynı beş şık** farklı cevapla geri geldi. Önceki sınavın cevabını taşıma, tarifi oku.',
      'Altsoy varken anne mirasçı olamaz; önce ölen oğlun payı çocuklarına bölünür.',
    ],
    ezber: [
      ['1 yıl', 'Boşanmadan doğan dava hakları, kesinleşmeden'],
      ['6 ay · 5 yıl', 'Zina ve hayata kastta dava: öğrenmeden, her hâlde olaydan'],
      ['1/4', 'Sağ eşin payı, altsoyla birlikte'],
      ['1/2', 'Altsoyun saklı payı, yasal payının yarısı'],
      ['3/8 · 3/16', 'Kız 3/8; önce ölen oğlun iki çocuğu ayrı ayrı 3/16'],
      ['7 kişi', 'Dernek kuruluşu'],
      ['5 + 5', 'Yönetim kurulu en az 5 asıl, 5 yedek (tüzük fazlasını koyabilir)'],
      ['3', 'Konfederasyon için en az federasyon'],
      ['30 yıl', 'Sürekli sayılan üst hakkı, en az'],
      ['100 yıl', 'Üst hakkının ve tüzel kişi intifasının üst sınırı'],
      ['5 yıl', 'Bulunmuş eşyada malikin ortaya çıkma süresi'],
      ['1 yıl', 'Ad değiştirmeye karşı dava, öğrenmeden'],
      ['6 ay', 'Gaiplik: ilk ilandan itibaren en az bekleme'],
      ['3 yıllık faiz', 'İpoteğin güvence kapsamı'],
    ],
    sinavda: 'Harf kodlu miras olaylarında soy ağacını kenara çiz. Boşanma havuzundan her sınav yaklaşık 3 soru geliyor.',
  },
  {
    id: 'borclar', ad: 'Borçlar Hukuku', aralik: [34, 45], soru: 12, ters: 43,
    ozet: 'Kira her sınavda; kural ile istisnayı ters çeviriyorlar.',
    cikan: [
      ['Kira (konut ve çatılı iş yeri)', 8, 4],
      ['Geçersizlik yaptırımları', 5, 3],
      ['Yarar ve hasarın geçişi', 4, 3],
      ['Zamanaşımı ve kesilmesi', 4, 3],
      ['Alacağın devri', 4, 2],
      ['Genel işlem koşulları, takas, tüketim ödüncü', 9, 3],
      ['Kefalet, ceza koşulu, müteselsil borç', 9, 3],
      ['İrade bozuklukları, haksız fiil, ayıp', 9, 3],
    ],
    tuzak: [
      { y: 'Zamanaşımı kefile karşı kesilince asıl borçluya karşı da kesilir.', d: 'Tersi doğru: asıl borçluya karşı kesilirse kefile karşı da kesilir.' },
      { y: 'Alıcı zilyetliği devralmada temerrüde düşse de hasar satıcıda kalır.', d: 'Hasar alıcıya geçer.' },
      { y: 'Satıcı ayıbı bilmiyorsa sorumlu olmaz.', d: 'Bilmese de sorumludur.' },
      { y: 'Hâkim, ağır kusurlu yükümlünün tazminatını yoksulluk sebebiyle resen indirir.', d: 'Kast ve ağır kusurda bu indirim yok.' },
      { y: 'Koşula bağlı hakkı tehlikeye düşen alacaklı önlem alamaz.', d: 'Koruma önlemi isteyebilir.' },
      { y: 'Genel işlem koşullarında tek yanlı değişiklik kaydı sözleşmeyi geçersiz kılar.', d: 'O kayıt yazılmamış sayılır, sözleşme ayakta kalır.' },
      '"Kesin olarak hükümsüzdür" ifadesi üç soruda geçti, **üçünde de doğruydu**. Mutlak ifadeyi refleksle eleme.',
      'Tarihli olayda süreyi **öğrenme** tarihinden başlat; sözleşme tarihinden başlatan için ayrı bir şık hazır.',
    ],
    ezber: [
      ['30 gün', 'Konut ve çatılı iş yeri kirasında kiracıya ödeme ihtarı'],
      ['3 aylık kira', 'Güvence bedelinin üst sınırı'],
      ['3 yıl', 'Tahliye sonrası eski kiracıdan başkasına kiralama yasağı'],
      ['6 hafta', 'Tüketim ödüncünde süre yoksa ilk istemden itibaren iade'],
      ['2 yıl · 10 yıl', 'Sebepsiz zenginleşme: öğrenmeden, her hâlde'],
      ['1 yıl', 'Aldatma ve gabinde bağlı olmadığını bildirme'],
      ['10 yıl', 'Borç senetle ikrar edilince işleyen yeni süre, her zaman'],
      ['20 yıl', 'Taşınmaz yapıda yüklenicinin ağır kusuru'],
    ],
    sinavda: 'Bloğun neredeyse yarısı ters kök. Her şıkta kuralın yönünü (kim, kime karşı, ne zaman) kontrol et.',
  },
  {
    id: 'ticaret', ad: 'Ticaret Hukuku', aralik: [46, 57], soru: 12, ters: 33,
    ozet: 'Kıymetli evrak ve şirketler bloğun dörtte üçü.',
    cikan: [
      ['Kıymetli evrak: poliçe, bono, çek', 16, 4],
      ['Şirketler: anonim, limited, özel denetim', 12, 4],
      ['Tacir, esnaf, ticaret sicili, unvan', 7, 4],
      ['Haksız rekabet', 4, 3],
      ['Acentelik', 2, 2],
    ],
    tuzak: [
      { y: 'Kısmi ciro mümkündür.', d: 'Ciro bölünemez; kısmi ciro batıldır.' },
      { y: 'Süresinde ihbar etmeyen başvurma hakkını kaybeder.', d: 'Kaybetmez; ihmalinden doğan zarardan sorumlu olur.' },
      { y: 'Şubeye ayrı sermaye tahsisi zorunludur.', d: 'Zorunlu değildir.' },
      { y: 'Limited şirket yalnızca ticari işletme işletmek için kurulur.', d: 'Kanunen yasak olmayan her ekonomik amaçla kurulabilir.' },
      'Özel denetimde merci **asliye ticaret mahkemesi**; SPK ve Bakanlık çeldirici.',
      'Acente, ticari temsilci, ticari vekil, simsar, tek satıcı: tarif hangisine uyuyor.',
    ],
    ezber: [
      ['1 yıl', 'Görüldüğünde ödemeli poliçenin ibrazı, düzenlemeden'],
      ['3 ay', 'Belirsiz süreli acentelikte fesih bildirimi'],
      ['2 iş günü', 'Araya girenin borçluya ihbarı'],
      ['%75', 'Anonimde işletme konusunu değiştiren karar, sermaye çoğunluğu'],
      ['2/3 + salt', 'Limitedde önemli kararlar: oyların üçte ikisi ve sermayenin salt çoğunluğu'],
      ['%10 · 1 ay', 'Anonim genel kurulda finansal tablo müzakeresini erteletme'],
    ],
    yok: 'Deniz ticareti ve sigorta hiç yok; simsarlık yalnız çeldirici.',
    sinavda: 'Kambiyoda süre soruları hızlı biter; kazandığın süreyi şirketler sorularına ver.',
  },
  {
    id: 'hmk', ad: 'Medeni Usul (HMK)', aralik: [58, 69], soru: 12, ters: 52,
    ozet: 'Ters kök rekortmeni: iki sorudan biri "yanlıştır".',
    cikan: [
      ['Süreler ve kesin süre', 7, 4],
      ['Yetki, yetki sözleşmesi, yetki itirazı', 4, 3],
      ['Feragat ve kabul', 3, 3],
      ['Islah, görev, istinaf', 6, 3],
      ['İspat, tedbir, teminat, ilk itiraz', 6, 3],
      ['Basit yargılama, yargılama ilkeleri', 4, 3],
    ],
    tuzak: [
      { y: 'Feragat mutlaka dilekçeyle, yazılı yapılır.', d: 'Sözlü de olur; tutanağa geçirilir.' },
      { y: 'Yetkili mahkemeyi göstermeyen yetki itirazı da dikkate alınır.', d: 'Yetkili mahkemeyi göstermek şart.' },
      { y: 'Şartlar değişse de hâkim teminatı artıramaz.', d: 'Artırabilir.' },
      { y: 'Tanık 18 yaşını bitirmemişse yeminsiz dinlenir.', d: '15 yaşını doldurmamışsa.' },
      'İstinafta karşı dava ve yetki sözleşmesi **yapılamaz**; mücbir sebeple gösterilemeyen delil **gösterilebilir**.',
      'Komşu kavramlar: tasarruf, taraflarca getirilme, taleple bağlılık; basit, bileşik, vasıflı ikrar.',
    ],
    ezber: [
      ['2 hafta', 'Cevap dilekçesi; bir defa, en çok 1 ay uzatılır'],
      ['2 hafta', 'İstinaf başvurusu'],
      ['1 hafta', 'Kesin süre: istinaf harç eksiği, talep sonucunun tamamlanması'],
      ['1 hafta', 'Tanık davetiyesi, duruşmadan en az bu kadar önce'],
      ['1 ay', 'Tedbir teminatının iadesi için tazminat davası'],
    ],
    yok: 'İstinaf ve temyiz parasal sınırı sayı olarak hiç verilmedi.',
    sinavda: 'Burada hız değil dikkat net getirir. Kökteki "yanlıştır" kelimesinin altını çiz.',
  },
  {
    id: 'icra', ad: 'İcra ve İflas', aralik: [70, 75], soru: 6, ters: 17,
    ozet: 'Haciz, iflas, konkordato her sınavda; yük sürelerde.',
    cikan: [
      ['Haciz ve haciz usulü', 8, 4],
      ['İflas', 5, 4],
      ['Konkordato ve mühlet', 4, 4],
      ['İcra mahkemesine şikâyet', 2, 2],
      ['İlamlı icra, icranın geri bırakılması', 2, 2],
    ],
    tuzak: [
      'Bononun aslının verilmemesi ya da vadenin gelmemesi: **7 gün** içinde **şikâyet**, **icra mahkemesi**. İki sınavda da aynı cevap; itiraz ve icra dairesi çeldirici.',
      'Süre yetmez, başlangıç anı: **ödeme emrinin tebliği**. İtirazın tebliği çeldirici.',
      { y: 'Mahkeme geçici mühleti resen uzatabilir.', d: 'Resen uzatamaz; uzatma kararına kanun yolu kapalı.' },
      { y: 'İflasın kapanmasıyla müflislik sıfatı kalkar.', d: 'Kalkmaz.' },
      { y: 'Şikâyet kural olarak tüm icra işlemlerini durdurur.', d: 'Durdurmaz; ilgililer gelmese de mahkeme karar verir.' },
      'İflas idaresi üyelerini **icra mahkemesi** seçer; asliye ticaret çeldirici.',
    ],
    ezber: [
      ['7 gün', 'Şikâyet süresi'],
      ['1 yıl · 3 gün', 'Haciz talebi, ödeme emri tebliğinden · icra dairesinin haczi yapması'],
      ['1 yıl', 'Genel iflas yolunda asliye ticarete başvuru, ödeme emri tebliğinden'],
      ['3 ay', 'Geçici mühlet (en çok 2 ay uzatılır)'],
      ['1 yıl', 'Kesin mühlet (en çok 6 ay uzatılır)'],
      ['10 gün', 'Duruşmasız işte icra mahkemesinin karar süresi'],
      ['2 hafta', 'İflasın kapanmasına karşı istinaf'],
    ],
    yok: 'İtirazın iptali ve kaldırılması ayrı soru değil; istihkak ve sıra cetveli hiç yok. Faiz, harç, konkordato oranı da yok.',
    sinavda: 'Ters kök az; soru doğrudan doğru hükmü istiyor. Bir soruda on ayrı süre kombinasyonu denendi, süreyi ve başlangıcını birlikte bil.',
  },
  {
    id: 'ceza', ad: 'Ceza Hukuku', aralik: [76, 84], soru: 9, ters: 17,
    ozet: 'Üçte ikisi genel hükümler; tuzak komşu kavramda.',
    cikan: [
      ['İçtima (zincirleme dahil)', 6, 3],
      ['İştirak', 4, 2],
      ['Teşebbüs, gönüllü vazgeçme', 2, 2],
      ['Kasten yaralama', 4, 4],
      ['Kasten öldürme', 4, 4],
      ['Hırsızlık ve yağma', 4, 3],
      ['Cinsel suçlar', 3, 2],
      ['Tekerrür, lehe kanun, müsadere, zamanaşımı', 6, 3],
    ],
    tuzak: [
      'Komşu kavram çiftleri: **şantaj ↔ tehdit ↔ yağma**, **yağma ↔ nitelikli hırsızlık**, **dolaylı faillik ↔ azmettirme**, **intihara yönlendirme ↔ öldürme**.',
      { y: 'Tekerrür süresi hükmün kesinleşmesinden başlar.', d: 'Cezanın infazından başlar; infaz edilmemiş ceza varken işlenen yeni suç tekerrür doğurur.' },
      { y: 'Müsadere ancak suç tamamlanınca mümkündür.', d: 'Tamamlanmasa da uygulanır.' },
      { y: 'İştirak kasten ve taksirle işlenen suçlarda geçerlidir.', d: 'Yalnız kasten işlenen suçlarda.' },
      'Suç sonucu gebelik 20 haftayı geçmemişse, hastanede uzman hekimin sonlandırması **suç değildir**.',
      '"Uzun şık doğrudur" burada çalışmıyor: doğru şık 35 sorunun yalnız 3\'ünde en uzundu.',
    ],
    ezber: [
      ['12 yaş', 'Doldurmamış çocuğun ceza sorumluluğu yok'],
      ['10 hafta', 'İsteğe bağlı gebeliği sonlandırma sınırı'],
      ['20 hafta', 'Suç sonucu gebelikte sınır'],
      ['5 yıl · 3 yıl', 'Tekerrür: 5 yıldan fazla hapiste 5 yıl, diğerlerinde 3 yıl, infazdan'],
      ['1/4 – 3/4', 'Teşebbüste indirim aralığı'],
    ],
    sinavda: 'Olaylı soruda önce suçun adını kendin koy, sonra şıklara bak. Blok dört sınavda da tam 9 soru.',
  },
  {
    id: 'cmk', ad: 'Ceza Muhakemesi (CMK)', aralik: [85, 90], soru: 6, ters: 46,
    ozet: 'Kural bilme dersi; merci kaydırması bir numaralı tuzak.',
    cikan: [
      ['Koruma tedbirleri', 4, 2],
      ['Tanıklık', 3, 3],
      ['Delil ve duruşma', 6, 3],
      ['Görev ve yetki', 3, 3],
      ['Müdafi, sorgu, KYO kararı', 6, 2],
    ],
    tuzak: [
      'Kovuşturmaya yer olmadığı kararına itiraz ve yeni delille dava: **sulh ceza hâkimliği**. Ağır ceza, BAM, HSK çeldirici.',
      'Suçun niteliği değişirse önce **ek savunma hakkı**; görevsizlik ve yetkisizlik çeldirici.',
      { y: 'Bilgisayarda arama ancak kovuşturma evresinde yapılır.', d: 'Soruşturmada da yapılır.' },
      { y: '18 yaş altı sanıkta duruşma kapalı, hüküm açık duruşmada açıklanır.', d: 'Hüküm de kapalı açıklanır.' },
      { y: 'Soruşturmada sorguda müdafi sayısı biri geçemez.', d: 'Üçü geçemez.' },
      { y: 'Seri muhakemede iştirakte bir şüphelinin kabulü yeter.', d: 'Tüm şüphelilerin kabulü gerekir.' },
      { y: 'Eski hâle getirme isteminin reddi kesindir.', d: 'İtiraz edilebilir.' },
      'Sorguda yasak yöntemler listesinde **gözetleme** yok.',
    ],
    ezber: [
      ['15 yaş', 'Doldurmamış tanık yeminsiz dinlenir (18 çeldirici)'],
      ['3', 'Soruşturmada ifade ve sorguda müdafi sayısı en çok; örgüt davasında duruşmada da en çok 3'],
      ['5 yıl', 'Alt sınırı 5 yıldan fazla hapis gerektiren suçta istinabeyle sorgu yok'],
      ['3 hafta', 'Gözlem altına alma; toplam en çok 3 ay'],
      ['2 hafta', 'Eski hâle getirme dilekçesi, engelin kalkmasından'],
    ],
    sinavda: 'Olay neredeyse yok. Koruma tedbirleri, tanıklık ve duruşma bloğun yarısından fazlası.',
  },
  {
    id: 'is', ad: 'İş ve Sosyal Güvenlik', aralik: [91, 96], soru: 6, ters: 33,
    ozet: 'Bireysel iş hukuku ve sayı: "hangi kuralda kaç gün".',
    cikan: [
      ['İş güvencesi, işe iade', 3, 3],
      ['Fesih', 3, 2],
      ['5510 sigorta kolları', 3, 3],
      ['Engelli çalıştırma', 2, 2],
      ['Geçici iş ilişkisi', 2, 2],
      ['Sendika üyeliği', 2, 2],
    ],
    tuzak: [
      'İşe iadede iki süre yer değiştiriyor: fesihten **1 ay** içinde arabulucu, son tutanaktan **2 hafta** içinde dava.',
      'İş güvencesi tazminatı en az **4**, en çok **8** aylık ücret; soru "en az" diye sordu.',
      'Engelli kotası: 50 ve üstü işçide **%3**; **çırak ve yer altı işçisi** sayılmaz.',
      'Hastalık ve kazada derhâl fesih: bildirim süresi **+ 6 hafta** aşılınca. 1 yıl kıdemde 4 + 6 = **10 hafta**.',
      { y: 'İşçi, sırf işyeri devredildi diye haklı nedenle derhâl feshedebilir.', d: 'Devir tek başına haklı neden değil.' },
    ],
    ezber: [
      ['6 iş günü', 'Haklı fesih hakkının kullanımı · esaslı değişikliğe itiraz'],
      ['1 ay · 2 hafta', 'Arabulucuya başvuru · son tutanaktan dava'],
      ['4 – 8 ay', 'İş güvencesi tazminatı'],
      ['2 saat', 'Yeni iş arama izni, günlük'],
      ['20 gün', 'Yıllık izin alt sınırı: 18 ve daha küçük, 50 ve üstü yaş'],
      ['15 yaş · 30 gün', 'Sendika üyelik yaşı · başvuru kabul sayılır'],
      ['5 işçi', '10 veya daha az işçili yerde geçici işçi sınırı'],
      ['2 yıl', 'İşyeri devrinde birlikte sorumluluk'],
      ['120 · 600 · 180', 'İşsizlik ödeneği: son 120 gün kesintisiz, 3 yılda 600 gün prim, 180 gün ödenek'],
      ['20 gün', 'Ücret ödenmezse iş görmekten kaçınma'],
    ],
    yok: 'Kıdem ve ihbar tazminatı hiç geçmedi.',
    sinavda: 'Birçok soruda beş şıkkın beşi de sayı. Sayı ezberi burada doğrudan net.',
  },
  {
    id: 'vergi', ad: 'Vergi ve Vergi Usul', aralik: [97, 102], soru: 6, ters: 23,
    ozet: 'Gelir unsurları ve tarh; şıklar çok kısa.',
    cikan: [
      ['Gelir unsurları ayrımı', 4, 3],
      ['VUK genel usul, tarh yöntemleri', 8, 4],
      ['Motorlu taşıtlar vergisi', 2, 2],
      ['KDV', 2, 2],
      ['Örtülü sermaye, ferî kamu alacağı', 2, 1],
    ],
    tuzak: [
      'Ücret, serbest meslek, ticari kazanç, gayrimenkul ve menkul sermaye iradı, değer artışı: tarif hangisine uyuyor. Son sınavda **art arda iki soru**.',
      'Gecikme faizi, gecikme zammı, tecil faizi yan yana konuluyor.',
      'KDV matrahına **ticari teamül iskontosu girmez**; vade farkı, kur farkı girer.',
      'VUK\'ta iştirak: muhasebe hilesi ve defter yok etme **evet**; defteri tasdik ettirmeme **hayır**.',
      'Vergi ziyaı: eksik tahakkuk ve haksız iade **evet**; geç tahsil **hayır**.',
    ],
    ezber: [
      ['%20', 'İzaha davette kesilen vergi ziyaı cezası'],
      ['3 kat', 'Örtülü sermaye: öz sermayenin üç katını aşan borç'],
    ],
    sinavda: 'İki öncüllü sorunun ikisi de "I ve II" ile çözüldü. "Hepsi" en az olası cevap.',
  },
  {
    id: 'avukatlik', ad: 'Avukatlık Hukuku', aralik: [103, 105], soru: 3, ters: 43,
    ozet: 'Liste ezberi: birleşen işler, ret sebepleri, organlar.',
    cikan: [
      ['Avukatlıkla birleşen işler', 2, 2],
      ['İşi reddetme zorunluluğu', 2, 2],
      ['Avukatlığa kabul ve engelleri', 2, 1],
      ['Hak, ödev, reklam yasağı', 2, 2],
      ['Disiplin, saklama, baro organları', 3, 2],
    ],
    tuzak: [
      '**Kademe ilerlemesinin durdurulması** avukatlık disiplin cezası değil, memur cezası.',
      'Daha önce **tanıklık** yapmış olmak ve **ikinci derece hısımlık** ret sebebi değil.',
      'Birleşir: hakemlik, belediye meclisi üyeliği, gazete sahipliği, tasfiye memurluğu. Birleşmez: sigorta prodüktörlüğü, esnaflık.',
      'Baro **genel sekreterliği** organ değil. **65 yaş** kabul engeli değil.',
      'Görev suçunda soruşturma izni ve uluslararası toplantı bildirimi: **Adalet Bakanlığı**. Barolar Birliği çeldirici.',
    ],
    ezber: [
      ['3 ay', 'Vekâlet bitince evrak saklama yükümlülüğü, bildirimden'],
      ['Ruhsatname', 'Avukatlığa kabul, ruhsatnamenin verildiği an hüküm doğurur'],
    ],
    yok: 'Avukatlık ücreti ve ücret sözleşmesi hiç sorulmadı.',
    sinavda: 'Kökün yarısı ters ("sayılmamıştır, değildir"). Listeyi bilen 5 saniyede çözer.',
  },
  {
    id: 'felsefe', ad: 'Hukuk Felsefesi', aralik: [106, 108], soru: 3, ters: 23,
    ozet: 'Soruların çoğu "bu düşünür kim?".',
    cikan: [
      ['Düşünürü tanıma', 8, 4],
      ['Hukuk sosyolojisi', 3, 3],
      ['Akımlar: doğal hukuk, pozitivizm, realizm, faydacılık', 4, 3],
    ],
    tuzak: [
      'Platon **Sokrates\'in**, Aristoteles **Platon\'un** öğrencisi. Üçü aynı şıklarda duruyor.',
      'Farabi ile İbni Haldun birbirinin çeldiricisi.',
      '**John Locke** dört kez çeldirici oldu, hiç doğru cevap olmadı.',
      '"Olamaz" sorusunda cevap akımın tam tersi: realizm için "hukuk kapalı bir sistemdir", Bentham için "bireysel menfaat ihmal edilir".',
    ],
    ezber: [
      ['Farabi', 'Medinetü\'l Fazıla, klasik doğal hukuk'],
      ['Platon', 'Devlet, Yasalar'],
      ['Aristoteles', 'Politika'],
      ['İbni Haldun', 'Mukaddime, ümran ilmi'],
      ['Hobbes', 'Leviathan, tabiat durumu'],
      ['Hegel', 'Diyalektik idealizm, mutlak ruh'],
      ['Durkheim', 'Toplumsal İşbölümü, mekanik dayanışma'],
      ['Montesquieu', 'Kanunların Ruhu, kuvvetler ayrılığı'],
      ['Bentham', 'Faydacılık'],
    ],
    sinavda: 'Mantıkla çözülmez, hatırlanır. Tabloyu bilen bloğu tamamlar.',
  },
  {
    id: 'tarih', ad: 'Türk Hukuk Tarihi', aralik: [109, 111], soru: 3, ters: 0,
    ozet: 'Ters kök hiç yok; tek doğru ad.',
    cikan: [
      ['Kadı yardımcıları', 2, 2],
      ['Mecelle', 2, 2],
      ['Divanlar, görevliler, vakıf türleri', 3, 2],
      ['Anayasal gelişmeler, kanun iktibasları', 2, 2],
    ],
    tuzak: [
      'Kadı yardımcıları beşlisi (Kassam, Naib, Muhzır, Ehl-i Hibre, Şuhûdü\'l-hal) iki sınavda **aynen** geldi, cevap farklıydı.',
      'Kronoloji: **Sened-i İttifak → Tanzimat → Islahat**. Yıl değil sıra soruluyor.',
    ],
    ezber: [
      ['Şuhûdü\'l-hal', 'Yargılamaya gözlemci olarak katılan'],
      ['Kassam', 'Miras mallarını paylaştıran, dava mahalline giden'],
      ['Mecelle', '1868–1876, 1851 madde, Ahmet Cevdet Paşa'],
      ['Memnu', 'Yasak'],
      ['Ayak Divanı', 'İvedi durumda padişah başkanlığında toplanan'],
      ['Nişancı', 'Tuğra çeken görevli'],
      ['Zürrî vakıf', 'Evlat ve soy yararına kurulan'],
      ['Şer\'iyye sicilleri', 'Osmanlı mahkeme kayıtları'],
      ['Kitabeler', 'Göktürk, Bilge Kağan ve Kül Tigin'],
      ['HUMK 1927', 'İsviçre Neuchâtel kantonundan'],
    ],
    sinavda: 'Kök okumaya süre gitmez, bütün süre hafızaya. Tahmin isabeti yüzde 20.',
  },
  {
    id: 'milletlerarasi', ad: 'Milletlerarası Hukuk', aralik: [112, 114], soru: 3, ters: 14,
    ozet: 'Andlaşma, BM, AİHM; doğru merci çoğu zaman Cumhurbaşkanı.',
    cikan: [
      ['Andlaşmalar hukuku', 4, 2],
      ['Birleşmiş Milletler', 2, 2],
      ['AİHS ve AİHM', 3, 2],
      ['Devletin tanınması, deniz alanları', 2, 2],
    ],
    tuzak: [
      { y: 'BM Genel Kurulunda her üyenin en çok 3 temsilcisi olur.', d: 'En çok 5.' },
      'BM\'nin yargı organı **Uluslararası Adalet Divanı**; Uluslararası Sürekli Adalet Divanı tarihî ve çeldirici.',
      'Örtülü tanıma **sayılmayan**: aynı uluslararası konferansa katılmak.',
      'İmzalanıp onaylanmamış protokole dayanan başvuru: **konu bakımından bağdaşmazlık**, kabul edilemez.',
    ],
    ezber: [
      ['Cumhurbaşkanı', 'Andlaşmayı onaylama'],
      ['Mutlak butlan', 'Jus cogens\'e aykırı andlaşma'],
      ['Yardımcı kaynak', 'Yargı kararları, asli kaynak değil'],
      ['2/3', 'Genel Kurulda önemli sorunlar'],
      ['Açık deniz', 'Hiçbir devletin egemenliğinde olmayan alan'],
    ],
    sinavda: 'MÖHUK ile aynı havuz gibi çalış; bir sınavda iki blok iç içe geçti.',
  },
  {
    id: 'mohuk', ad: 'Milletlerarası Özel Hukuk', aralik: [115, 117], soru: 3, ters: 33,
    ozet: 'Her sınavda üç kanun: 5901, 6458, 5718.',
    cikan: [
      ['5901 Türk Vatandaşlığı', 3, 3],
      ['6458 Yabancılar ve Uluslararası Koruma', 2, 2],
      ['5718 MÖHUK: tenfiz, miras, eşya', 3, 3],
    ],
    tuzak: [
      'Merci ikilisi birbirinin tersi: vatandaşlığı **kaybettirme Cumhurbaşkanı**, kazanmada millî güvenlik engeliyle **reddeden İçişleri Bakanlığı**.',
      { y: 'Kısmen tenfiz mümkün değildir.', d: 'Mümkündür.' },
      { y: 'Türkiye\'deki mirasçısız tereke ölenin vatandaşı olduğu devlete kalır.', d: 'Devlete (Türkiye\'ye) kalır.' },
      '6 ay içinde çalışma izni için başvurmamak koruma statüsünü **sona erdirmez**.',
    ],
    ezber: [
      ['Resmî Gazete', 'Kaybettirme kararı yayımla hüküm doğurur'],
      ['Durdurur', 'Tenfiz isteminin reddine karşı temyiz, yerine getirmeyi'],
      ['Türk hukuku', 'Türkiye\'deki taşınmaz, yabancı eşler dahil'],
    ],
    sinavda: 'Etikete değil kanun numarasına göre çalış. Olay soruları merci sorusuna dönüşüyor.',
  },
  {
    id: 'genelkamu', ad: 'Genel Kamu Hukuku', aralik: [118, 120], soru: 3, ters: 17,
    ozet: 'Yarısı AİHS; kalanı temel kavram.',
    cikan: [
      ['AİHS ve AİHM', 3, 1],
      ['Demokrasi araçları, statü hakları, devlet', 3, 3],
    ],
    tuzak: [
      'OHAL\'de dahi askıya alınamaz: yaşam (meşru savaş hariç), işkence, kölelik, kanunsuz ceza. **Zorla çalıştırma listede yok**; cevap "I ve III" idi.',
      'Geçici tedbir **Sözleşmede değil, AİHM İçtüzüğünde**. İki soru aynı bilginin iki yüzü.',
      '**Kamu hukuku tüzel kişileri** AİHM\'e bireysel başvuru yapamaz; özel hukuk tüzel kişileri yapabilir.',
    ],
    ezber: [
      ['Halk teşebbüsü', 'İmza toplanır, parlamento görüşmek zorunda'],
      ['Sosyal güvenlik', 'Negatif statü hakkı olmayan (pozitif statü)'],
      ['Tüzel kişilik', 'Devletin borçlanması, sözleşme ve dava ehliyeti'],
    ],
    sinavda: 'Anayasa Yargısındaki bireysel başvuru sorularıyla birlikte çalış.',
  },
];

/* Taktik sayfası: sınavın tamamına dair ölçülen kurallar */
export const TAKTIK = [
  { b: 'Boş bırakma', t: 'Yanlış doğruyu götürmüyor. Son dakikada boş kalanları işaretle.' },
  { b: 'Her 3-4 sorudan biri ters kök', t: '"Değildir, yanlıştır, sayılmamıştır" 460 sorunun %30\'u. HMK, CMK, İYUK, Borçlar ve Avukatlıkta yarıya yakın.' },
  { b: 'Öncüllüde bir öncülü kesin ele', t: 'Üç öncüllü sorularda cevap %67 iki öncül birleşimi; "I, II ve III" yalnız %8. Kesin yanlış bulduğun öncülü içeren şıkları çiz, 5 şık 2\'ye iner.' },
  { b: '90 saniye sınırı', t: 'Soru başına ortalama 77,5 saniye. 90\'ı geçeni işaretle, dönüşte gel.' },
  { b: 'Sondan başlamak bir seçenek', t: '97–120 arası 24 soru tanım ve kimlik sorusu, şıklar çok kısa. Önce onları bitirip kazandığın süreyi Medeni, Borçlar ve HMK\'ya aktarabilirsin.' },
  { b: 'Harf tahmini yapma', t: 'Cevap harflerinin dağılımı istatistik olarak anlamlı değil. Kararsızlıkta öncül eleme ve kök okuma kazandırır.' },
];

export const ZAMAN = [
  ['1–18', 'Anayasa, AYM, İdare, İYUK', 22],
  ['19–33', 'Medeni Hukuk', 24],
  ['34–45', 'Borçlar', 20],
  ['46–57', 'Ticaret', 16],
  ['58–69', 'HMK', 18],
  ['70–81', 'İcra, Ceza', 18],
  ['82–96', 'Ceza, CMK, İş', 20],
  ['97–120', 'Vergi\'den Genel Kamu\'ya', 17],
];
